[package]
name = "rhizome-moss-derive"
version = "0.1.0"
edition = "2024"
description = "Derive macros for moss"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
