[alias]
xtask = "run --package xtask --"

# For faster builds with mold linker (local only), add to the end of this file:
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]
